 version: '2'
 services:
   db:
     image: mdillon/postgis
   web:
     build: .
     command: gunicorn --workers=4 -b 0.0.0.0:8000 GuppiesWechat.wsgi
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db
