 version: '2'
 services:
   db:
     image: mdillon/postgis
     volumes:
      - .data/postgres:/var/lib/postgresql/data
   web:
     build: .
     command: bash -c "./manage.py migrate && gunicorn --workers=8 -b 0.0.0.0:8001 GuppiesWechat.wsgi"
     volumes:
       - .:/code
     ports:
       - "8001:8001"
     depends_on:
       - db
     environment:
       DJANGO_SETTINGS_MODULE: GuppiesWechat.settings-production
