 version: '2'
 services:
   test_db:
     image: mdillon/postgis
     volumes:
      - .data/test_postgres:/var/lib/postgresql/data
   test_web:
     build: .
     command: bash -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8002"
     volumes:
       - .:/code
     ports:
       - "8002:8002"
     depends_on:
       - test_db
